spring.application.name=mavecito
spring.dataSource.url = jdbc:mysql://127.0.0.1:3306/tienda
spring.dataSource.username = root
spring.dataSource.driver-class-main= com.mysql.cj.jdbc.driver
spring.dataSource.jpa.database-platform = org.hibernate.dialect.mysql95dialect
spring.dataSource.initialization-mode = always
spring.jpa.hibernate.ddl-auto = update

